default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432

development:
  <<: *default
  database: codhab_development
  username: postgres
  password: <%= ENV['DB_PASS'] %>
  host: localhost

test:
  <<: *default
  database: codhab_test
  username: postgres
  password: <%= ENV['DB_PASS'] %>
  host: localhost
  schema_search_path: extranet
